name: Node.js CI

on: 
  pull_request:
    branches: [main]

jobs: 
  test_pr: 
    runs-on: macos-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with: 
          node-version: latest
      - run: npm ci
      - run: npm test
      - run: npm build
